# Generated by Django 2.2.6 on 2019-11-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='id_friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('owe', models.IntegerField()),
                ('lent', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
