# Generated by Django 2.2.6 on 2019-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_trans',
            name='obf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='id_trans',
            name='obu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='id_trans',
            name='pbf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='id_trans',
            name='pbu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
