# Generated by Django 2.2.6 on 2019-11-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20191123_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='grp_trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('gid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('owe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='grp_trans_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('desc', models.TextField(default='')),
            ],
        ),
    ]
